name: robot_scraper_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  page_transition: ^2.0.9
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/chicken.png
    
  
  
